# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from table import Ui_Form

class Ui_MainWindow(object):

    def show_pop_up(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Form()
        self.ui.setupUi(self.window, "Memoria")
        self.window.show()


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(779, 689)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout_2.addWidget(self.lcdNumber, 1, 0, 1, 1)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout_2.addWidget(self.lcdNumber_2, 1, 1, 1, 1)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber_3.setDigitCount(4)
        self.lcdNumber_3.setMode(QtWidgets.QLCDNumber.Dec)

        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.gridLayout_2.addWidget(self.lcdNumber_3, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_2.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_2.addWidget(self.checkBox_3)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setSpacing(50)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.botaoMemDados = QtWidgets.QPushButton(self.frame_3)
        self.botaoMemDados.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.botaoMemDados.setFont(font)
        self.botaoMemDados.setStyleSheet("QPushButton{\n"
                                        "    border-radius: 30px;\n"
                                        "    background: rgb(190, 190, 190);\n"
                                        "    color: black\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover{\n"
                                        "    background: rgba(190, 190, 190, 220);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed{\n"
                                        "    background: rgba(190, 190, 190, 180)\n"
                                        "}")
        self.botaoMemDados.setObjectName("botaoMemDados")
        self.horizontalLayout_3.addWidget(self.botaoMemDados)
        self.botaoMemProg = QtWidgets.QPushButton(self.frame_3)
        self.botaoMemProg.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.botaoMemProg.setFont(font)
        self.botaoMemProg.setStyleSheet("QPushButton{\n"
"    border-radius: 30px;\n"
"    background: rgb(190, 190, 190);\n"
"    color: black\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background: rgba(190, 190, 190, 220);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background: rgba(190, 190, 190, 180)\n"
"}")
        self.botaoMemProg.setObjectName("botaoMemProg")
        self.horizontalLayout_3.addWidget(self.botaoMemProg)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 779, 21))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuAbrir = QtWidgets.QMenu(self.menuArquivo)
        self.menuAbrir.setObjectName("menuAbrir")
        self.menuSalvar = QtWidgets.QMenu(self.menuArquivo)
        self.menuSalvar.setObjectName("menuSalvar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir_Memoria_de_Dados = QtWidgets.QAction(MainWindow)
        self.actionAbrir_Memoria_de_Dados.setObjectName("actionAbrir_Memoria_de_Dados")
        self.actionMemoria_de_Dados = QtWidgets.QAction(MainWindow)
        self.actionMemoria_de_Dados.setObjectName("actionMemoria_de_Dados")
        self.actionMemoria_de_Programa = QtWidgets.QAction(MainWindow)
        self.actionMemoria_de_Programa.setObjectName("actionMemoria_de_Programa")
        self.actionMemoria_de_Dados_2 = QtWidgets.QAction(MainWindow)
        self.actionMemoria_de_Dados_2.setObjectName("actionMemoria_de_Dados_2")
        self.actionMemoria_de_Programa_2 = QtWidgets.QAction(MainWindow)
        self.actionMemoria_de_Programa_2.setObjectName("actionMemoria_de_Programa_2")
        self.menuAbrir.addAction(self.actionMemoria_de_Dados)
        self.menuAbrir.addAction(self.actionMemoria_de_Programa)
        self.menuSalvar.addAction(self.actionMemoria_de_Dados_2)
        self.menuSalvar.addAction(self.actionMemoria_de_Programa_2)
        self.menuArquivo.addAction(self.menuSalvar.menuAction())
        self.menuArquivo.addAction(self.menuAbrir.menuAction())
        self.menubar.addAction(self.menuArquivo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.botaoMemDados.clicked.connect(self.show_pop_up)
        self.botaoMemProg.clicked.connect(self.show_pop_up)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BIPy"))
        self.label.setText(_translate("MainWindow", "Instrução"))
        self.label_3.setText(_translate("MainWindow", "Acumulador"))
        self.label_2.setText(_translate("MainWindow", "PC"))
        self.checkBox.setText(_translate("MainWindow", "Reset"))
        self.checkBox_2.setText(_translate("MainWindow", "Halt"))
        self.checkBox_3.setText(_translate("MainWindow", "Step"))
        self.botaoMemDados.setText(_translate("MainWindow", "Memoria de Dados"))
        self.botaoMemProg.setText(_translate("MainWindow", "Memoria de Programa"))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo"))
        self.menuAbrir.setTitle(_translate("MainWindow", "Carregar"))
        self.menuSalvar.setTitle(_translate("MainWindow", "Salvar"))
        self.actionAbrir_Memoria_de_Dados.setText(_translate("MainWindow", "Abrir Memoria de Dados"))
        self.actionMemoria_de_Dados.setText(_translate("MainWindow", "Memoria de Dados"))
        self.actionMemoria_de_Programa.setText(_translate("MainWindow", "Memoria de Programa"))
        self.actionMemoria_de_Dados_2.setText(_translate("MainWindow", "Memoria de Dados"))
        self.actionMemoria_de_Programa_2.setText(_translate("MainWindow", "Memoria de Programa"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
