# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Pedro\OneDrive - Instituto Maua de Tecnologia\3º ano\Arquitetura\BIPy\processador_bip_em_python\src\GUI\MemoriaDados.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Memoria_de_Dados(object):
    def setupUi(self, Memoria_de_Dados):
        Memoria_de_Dados.setObjectName("Memoria_de_Dados")
        Memoria_de_Dados.resize(1030, 664)
        Memoria_de_Dados.setMinimumSize(QtCore.QSize(300, 300))
        Memoria_de_Dados.setMaximumSize(QtCore.QSize(1030, 100000))
        Memoria_de_Dados.setStyleSheet("QTableWidget{\n"
"    background: rgba(0, 71, 133,0.2);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Memoria_de_Dados)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setDragEnabled(True)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tableWidget.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideNone)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setRowCount(256)
        self.tableWidget.setColumnCount(16)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.horizontalLayout.addWidget(self.tableWidget)
        Memoria_de_Dados.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Memoria_de_Dados)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1030, 21))
        self.menubar.setObjectName("menubar")
        Memoria_de_Dados.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Memoria_de_Dados)
        self.statusbar.setObjectName("statusbar")
        Memoria_de_Dados.setStatusBar(self.statusbar)

        self.retranslateUi(Memoria_de_Dados)
        QtCore.QMetaObject.connectSlotsByName(Memoria_de_Dados)

    def retranslateUi(self, Memoria_de_Dados):
        _translate = QtCore.QCoreApplication.translate
        Memoria_de_Dados.setWindowTitle(_translate("Memoria_de_Dados", "Memoria de Dados"))
